apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacegame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacegame
  template:
    metadata:
      labels:
        app: spacegame
    spec:
      containers:
      - name: spacegame
        image: nginx 
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
