apiVersion: v1
kind: Service
metadata:
  name: spacegame-svc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /
spec:
  type: LoadBalancer
  selector:
    app: spacegame
  ports:
  - name: http
    port: 80
    targetPort: 8080
